.TH "ansi_codes" 3 "Version v2.0.0" "SLog - Sh*tty Logging" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ansi_codes \- ANSI escape sequences\&.
.SH SYNOPSIS
.br
.PP
.SS "Macros"

.in +1c
.ti -1c
.RI "#define \fBSLOG_ANSI_RESET\fP   '\\033[0m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_BOLD\fP   '\\033[1m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_RED\fP   '\\033[0;31m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_GREEN\fP   '\\033[0;32m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_YELLOW\fP   '\\033[0;33m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_CYAN\fP   '\\033[0;36m'"
.br
.ti -1c
.RI "#define \fBSLOG_ANSI_GRAY\fP   '\\033[0;37m'"
.br
.in -1c
.SH "Detailed Description"
.PP 

.SH "Macro Definition Documentation"
.PP 
.SS "#define SLOG_ANSI_BOLD   '\\033[1m'"
ANSI escape code for bold text\&. 
.SS "#define SLOG_ANSI_CYAN   '\\033[0;36m'"
ANSI escape code for cyan foreground color\&. 
.SS "#define SLOG_ANSI_GRAY   '\\033[0;37m'"
ANSI escape code for gray foreground color\&. 
.SS "#define SLOG_ANSI_GREEN   '\\033[0;32m'"
ANSI escape code for green foreground color\&. 
.SS "#define SLOG_ANSI_RED   '\\033[0;31m'"
ANSI escape code for red foreground color\&. 
.SS "#define SLOG_ANSI_RESET   '\\033[0m'"
ANSI escape code for reset\&. 
.SS "#define SLOG_ANSI_YELLOW   '\\033[0;33m'"
ANSI escape code for yellow foreground color\&. 
.SH "Author"
.PP 
Generated automatically by Doxygen for SLog - Sh*tty Logging from the source code\&.
